<%
	String mPais = "";
	try {
		mPais = session.getAttribute("temp_solicitante_v2_pre_pais_de_nacimiento_lkup").toString();
	} catch (Exception ex) {
		// catch the error and keep on going
	}		 
%>
<option value=""></option>
<option value="Afganistán"<% if (mPais.equals("Afganistán")) {%> selected <% } %>>Afganistán</option>
<option value="Albania"<% if (mPais.equals("Albania")) {%> selected <% } %>>Albania</option>
<option value="Alemania"<% if (mPais.equals("Alemania")) {%> selected <% } %>>Alemania</option>
<option value="Andorra"<% if (mPais.equals("Andorra")) {%> selected <% } %>>Andorra</option>
<option value="Anguila"<% if (mPais.equals("Anguila")) {%> selected <% } %>>Anguila</option>
<option value="Antigua y Barbuda"<% if (mPais.equals("Antigua y Barbuda")) {%> selected <% } %>>Antigua y Barbuda</option>
<option value="Antillas Holandesas"<% if (mPais.equals("Antillas Holandesas")) {%> selected <% } %>>Antillas Holandesas</option>
<option value="Arabia Saudita"<% if (mPais.equals("Arabia Saudita")) {%> selected <% } %>>Arabia Saudita</option>
<option value="Argelia"<% if (mPais.equals("Argelia")) {%> selected <% } %>>Argelia</option>
<option value="Argentina"<% if (mPais.equals("Argentina")) {%> selected <% } %>>Argentina</option>
<option value="Aruba"<% if (mPais.equals("Aruba")) {%> selected <% } %>>Aruba</option>
<option value="Australia"<% if (mPais.equals("Australia")) {%> selected <% } %>>Australia</option>
<option value="Austria"<% if (mPais.equals("Austria")) {%> selected <% } %>>Austria</option>
<option value="Bahamas"<% if (mPais.equals("Bahamas")) {%> selected <% } %>>Bahamas</option>
<option value="Bangladés/Bangladesh"<% if (mPais.equals("Bangladés/Bangladesh")) {%> selected <% } %>>Bangladés/Bangladesh</option>
<option value="Barbados"<% if (mPais.equals("Barbados")) {%> selected <% } %>>Barbados</option>
<option value="Barbuda"<% if (mPais.equals("Barbuda")) {%> selected <% } %>>Barbuda</option>
<option value="Bélgica"<% if (mPais.equals("Bélgica")) {%> selected <% } %>>Bélgica</option>
<option value="Belice"<% if (mPais.equals("Belice")) {%> selected <% } %>>Belice</option>
<option value="Benín"<% if (mPais.equals("Benín")) {%> selected <% } %>>Benín</option>
<option value="Birmania"<% if (mPais.equals("Birmania")) {%> selected <% } %>>Birmania</option>
<option value="Bolivia"<% if (mPais.equals("Bolivia")) {%> selected <% } %>>Bolivia</option>
<option value="Bonaire"<% if (mPais.equals("Bonaire")) {%> selected <% } %>>Bonaire</option>
<option value="Botswana"<% if (mPais.equals("Botswana")) {%> selected <% } %>>Botswana</option>
<option value="Brasil"<% if (mPais.equals("Brasil")) {%> selected <% } %>>Brasil</option>
<option value="Bulgaria"<% if (mPais.equals("Bulgaria")) {%> selected <% } %>>Bulgaria</option>
<option value="Burkina Faso"<% if (mPais.equals("Burkina Faso")) {%> selected <% } %>>Burkina Faso</option>
<option value="Camboya"<% if (mPais.equals("Camboya")) {%> selected <% } %>>Camboya</option>
<option value="Camerún"<% if (mPais.equals("Camerún")) {%> selected <% } %>>Camerún</option>
<option value="Canadá"<% if (mPais.equals("Canadá")) {%> selected <% } %>>Canadá</option>
<option value="Ceilán"<% if (mPais.equals("Ceilán")) {%> selected <% } %>>Ceilán</option>
<option value="Chad"<% if (mPais.equals("Chad")) {%> selected <% } %>>Chad</option>
<option value="Chile"<% if (mPais.equals("Chile")) {%> selected <% } %>>Chile</option>
<option value="China"<% if (mPais.equals("China")) {%> selected <% } %>>China</option>
<option value="Chipre"<% if (mPais.equals("Chipre")) {%> selected <% } %>>Chipre</option>
<option value="Colombia"<% if (mPais.equals("Colombia")) {%> selected <% } %>>Colombia</option>
<option value="Congo"<% if (mPais.equals("Congo")) {%> selected <% } %>>Congo</option>
<option value="Corea del Norte"<% if (mPais.equals("Corea del Norte")) {%> selected <% } %>>Corea del Norte</option>
<option value="Corea del Sur"<% if (mPais.equals("Corea del Sur")) {%> selected <% } %>>Corea del Sur</option>
<option value="Costa de Marfil"<% if (mPais.equals("Costa de Marfil")) {%> selected <% } %>>Costa de Marfil</option>
<option value="Costa Rica"<% if (mPais.equals("Costa Rica")) {%> selected <% } %>>Costa Rica</option>
<option value="Croacia"<% if (mPais.equals("Croacia")) {%> selected <% } %>>Croacia</option>
<option value="Cuba"<% if (mPais.equals("Cuba")) {%> selected <% } %>>Cuba</option>
<option value="Curazao"<% if (mPais.equals("Curazao")) {%> selected <% } %>>Curazao</option>
<option value="Dinamarca"<% if (mPais.equals("Dinamarca")) {%> selected <% } %>>Dinamarca</option>
<option value="Dominica"<% if (mPais.equals("Dominica")) {%> selected <% } %>>Dominica</option>
<option value="Dubai"<% if (mPais.equals("Dubai")) {%> selected <% } %>>Dubai</option>
<option value="Ecuador"<% if (mPais.equals("Ecuador")) {%> selected <% } %>>Ecuador</option>
<option value="Egipto"<% if (mPais.equals("Egipto")) {%> selected <% } %>>Egipto</option>
<option value="El Salvador"<% if (mPais.equals("El Salvador")) {%> selected <% } %>>El Salvador</option>
<option value="Eritrea"<% if (mPais.equals("Eritrea")) {%> selected <% } %>>Eritrea</option>
<option value="Escocia"<% if (mPais.equals("Escocia")) {%> selected <% } %>>Escocia</option>
<option value="Eslovaquia"<% if (mPais.equals("Eslovaquia")) {%> selected <% } %>>Eslovaquia</option>
<option value="España"<% if (mPais.equals("España")) {%> selected <% } %>>España</option>
<option value="Estados Unidos"<% if (mPais.equals("Estados Unidos")) {%> selected <% } %>>Estados Unidos</option>
<option value="Etiopía"<% if (mPais.equals("Etiopía")) {%> selected <% } %>>Etiopía</option>
<option value="Filipinas"<% if (mPais.equals("Filipinas")) {%> selected <% } %>>Filipinas</option>
<option value="Finlandia"<% if (mPais.equals("Finlandia")) {%> selected <% } %>>Finlandia</option>
<option value="Francia"<% if (mPais.equals("Francia")) {%> selected <% } %>>Francia</option>
<option value="Gabón"<% if (mPais.equals("Gabón")) {%> selected <% } %>>Gabón</option>
<option value="Gales"<% if (mPais.equals("Gales")) {%> selected <% } %>>Gales</option>
<option value="Gambia"<% if (mPais.equals("Gambia")) {%> selected <% } %>>Gambia</option>
<option value="Ghana"<% if (mPais.equals("Ghana")) {%> selected <% } %>>Ghana</option>
<option value="Gran Bretaña"<% if (mPais.equals("Gran Bretaña")) {%> selected <% } %>>Gran Bretaña</option>
<option value="Granada"<% if (mPais.equals("Granada")) {%> selected <% } %>>Granada</option>
<option value="Grecia"<% if (mPais.equals("Grecia")) {%> selected <% } %>>Grecia</option>
<option value="Guadalupe"<% if (mPais.equals("Guadalupe")) {%> selected <% } %>>Guadalupe</option>
<option value="Guam"<% if (mPais.equals("Guam")) {%> selected <% } %>>Guam</option>
<option value="Guatemala"<% if (mPais.equals("Guatemala")) {%> selected <% } %>>Guatemala</option>
<option value="Guinea"<% if (mPais.equals("Guinea")) {%> selected <% } %>>Guinea</option>
<option value="Guinea Ecuatorial"<% if (mPais.equals("Guinea Ecuatorial")) {%> selected <% } %>>Guinea Ecuatorial</option>
<option value="Guinea-Bissau"<% if (mPais.equals("Guinea-Bissau")) {%> selected <% } %>>Guinea-Bissau</option>
<option value="Guyana"<% if (mPais.equals("Guyana")) {%> selected <% } %>>Guyana</option>
<option value="Haití"<% if (mPais.equals("Haití")) {%> selected <% } %>>Haití</option>
<option value="Hawaii"<% if (mPais.equals("Hawaii")) {%> selected <% } %>>Hawaii</option>
<option value="Holanda"<% if (mPais.equals("Holanda")) {%> selected <% } %>>Holanda</option>
<option value="Honduras"<% if (mPais.equals("Honduras")) {%> selected <% } %>>Honduras</option>
<option value="India"<% if (mPais.equals("India")) {%> selected <% } %>>India</option>
<option value="Indonesia"<% if (mPais.equals("Indonesia")) {%> selected <% } %>>Indonesia</option>
<option value="Inglaterra"<% if (mPais.equals("Inglaterra")) {%> selected <% } %>>Inglaterra</option>
<option value="Irak, Iraq"<% if (mPais.equals("Irak, Iraq")) {%> selected <% } %>>Irak, Iraq</option>
<option value="Irán"<% if (mPais.equals("Irán")) {%> selected <% } %>>Irán</option>
<option value="Irlanda"<% if (mPais.equals("Irlanda")) {%> selected <% } %>>Irlanda</option>
<option value="Islandia"<% if (mPais.equals("Islandia")) {%> selected <% } %>>Islandia</option>
<option value="Islas Caimán"<% if (mPais.equals("Islas Caimán")) {%> selected <% } %>>Islas Caimán</option>
<option value="Islas Turcas y Caicos"<% if (mPais.equals("Islas Turcas y Caicos")) {%> selected <% } %>>Islas Turcas y Caicos</option>
<option value="Islas Vírgenes Británicas"<% if (mPais.equals("Islas Vírgenes Británicas")) {%> selected <% } %>>Islas Vírgenes Británicas</option>
<option value="Islas Vírgenes de Estados Unidos"<% if (mPais.equals("Islas Vírgenes de Estados Unidos")) {%> selected <% } %>>Islas Vírgenes de Estados Unidos</option>
<option value="Israel"<% if (mPais.equals("Israel")) {%> selected <% } %>>Israel</option>
<option value="Italia"<% if (mPais.equals("Italia")) {%> selected <% } %>>Italia</option>
<option value="Jamaica"<% if (mPais.equals("Jamaica")) {%> selected <% } %>>Jamaica</option>
<option value="Japón"<% if (mPais.equals("Japón")) {%> selected <% } %>>Japón</option>
<option value="Jordania"<% if (mPais.equals("Jordania")) {%> selected <% } %>>Jordania</option>
<option value="Kenya"<% if (mPais.equals("Kenya")) {%> selected <% } %>>Kenya</option>
<option value="Kuwait"<% if (mPais.equals("Kuwait")) {%> selected <% } %>>Kuwait</option>
<option value="Laos"<% if (mPais.equals("Laos")) {%> selected <% } %>>Laos</option>
<option value="las Islas Cook"<% if (mPais.equals("las Islas Cook")) {%> selected <% } %>>las Islas Cook</option>
<option value="Líbano"<% if (mPais.equals("Líbano")) {%> selected <% } %>>Líbano</option>
<option value="Liberia"<% if (mPais.equals("Liberia")) {%> selected <% } %>>Liberia</option>
<option value="Libia"<% if (mPais.equals("Libia")) {%> selected <% } %>>Libia</option>
<option value="Lituania"<% if (mPais.equals("Lituania")) {%> selected <% } %>>Lituania</option>
<option value="Luxemburgo"<% if (mPais.equals("Luxemburgo")) {%> selected <% } %>>Luxemburgo</option>
<option value="Malasia"<% if (mPais.equals("Malasia")) {%> selected <% } %>>Malasia</option>
<option value="Mali"<% if (mPais.equals("Mali")) {%> selected <% } %>>Mali</option>
<option value="Malta"<% if (mPais.equals("Malta")) {%> selected <% } %>>Malta</option>
<option value="Marruecos"<% if (mPais.equals("Marruecos")) {%> selected <% } %>>Marruecos</option>
<option value="Martinique"<% if (mPais.equals("Martinique")) {%> selected <% } %>>Martinique</option>
<option value="Mauricio"<% if (mPais.equals("Mauricio")) {%> selected <% } %>>Mauricio</option>
<option value="Mauritania"<% if (mPais.equals("Mauritania")) {%> selected <% } %>>Mauritania</option>
<option value="México, Méjico"<% if (mPais.equals("México, Méjico")) {%> selected <% } %>>México, Méjico</option>
<option value="Mónaco"<% if (mPais.equals("Mónaco")) {%> selected <% } %>>Mónaco</option>
<option value="Montserrat"<% if (mPais.equals("Montserrat")) {%> selected <% } %>>Montserrat</option>
<option value="Namibia"<% if (mPais.equals("Namibia")) {%> selected <% } %>>Namibia</option>
<option value="Nepal"<% if (mPais.equals("Nepal")) {%> selected <% } %>>Nepal</option>
<option value="Nicaragua"<% if (mPais.equals("Nicaragua")) {%> selected <% } %>>Nicaragua</option>
<option value="Niger"<% if (mPais.equals("Niger")) {%> selected <% } %>>Niger</option>
<option value="Nigeria"<% if (mPais.equals("Nigeria")) {%> selected <% } %>>Nigeria</option>
<option value="Noruega"<% if (mPais.equals("Noruega")) {%> selected <% } %>>Noruega</option>
<option value="Nueva Zelanda"<% if (mPais.equals("Nueva Zelanda")) {%> selected <% } %>>Nueva Zelanda</option>
<option value="Países Bajos"<% if (mPais.equals("Países Bajos")) {%> selected <% } %>>Países Bajos</option>
<option value="Palestina"<% if (mPais.equals("Palestina")) {%> selected <% } %>>Palestina</option>
<option value="Panamá"<% if (mPais.equals("Panamá")) {%> selected <% } %>>Panamá</option>
<option value="Paquistán"<% if (mPais.equals("Paquistán")) {%> selected <% } %>>Paquistán</option>
<option value="Paraguay"<% if (mPais.equals("Paraguay")) {%> selected <% } %>>Paraguay</option>
<option value="Persia"<% if (mPais.equals("Persia")) {%> selected <% } %>>Persia</option>
<option value="Perú"<% if (mPais.equals("Perú")) {%> selected <% } %>>Perú</option>
<option value="Polonia"<% if (mPais.equals("Polonia")) {%> selected <% } %>>Polonia</option>
<option value="Portugal"<% if (mPais.equals("Portugal")) {%> selected <% } %>>Portugal</option>
<option value="Puerto Rico"<% if (mPais.equals("Puerto Rico")) {%> selected <% } %>>Puerto Rico</option>
<option value="República Checa"<% if (mPais.equals("República Checa")) {%> selected <% } %>>República Checa</option>
<option value="República Dominicana"<% if (mPais.equals("República Dominicana")) {%> selected <% } %>>República Dominicana</option>
<option value="Ruanda"<% if (mPais.equals("Ruanda")) {%> selected <% } %>>Ruanda</option>
<option value="Rumanía"<% if (mPais.equals("Rumanía")) {%> selected <% } %>>Rumanía</option>
<option value="Rusia"<% if (mPais.equals("Rusia")) {%> selected <% } %>>Rusia</option>
<option value="Saba"<% if (mPais.equals("Saba")) {%> selected <% } %>>Saba</option>
<option value="Samoa"<% if (mPais.equals("Samoa")) {%> selected <% } %>>Samoa</option>
<option value="San Bartolomé"<% if (mPais.equals("San Bartolomé")) {%> selected <% } %>>San Bartolomé</option>
<option value="San Cristóbal y Nieves"<% if (mPais.equals("San Cristóbal y Nieves")) {%> selected <% } %>>San Cristóbal y Nieves</option>
<option value="San Eustaquio"<% if (mPais.equals("San Eustaquio")) {%> selected <% } %>>San Eustaquio</option>
<option value="San Martín"<% if (mPais.equals("San Martín")) {%> selected <% } %>>San Martín</option>
<option value="San Vicente"<% if (mPais.equals("San Vicente")) {%> selected <% } %>>San Vicente</option>
<option value="Santa Lucía"<% if (mPais.equals("Santa Lucía")) {%> selected <% } %>>Santa Lucía</option>
<option value="Santo Tomás"<% if (mPais.equals("Santo Tomás")) {%> selected <% } %>>Santo Tomás</option>
<option value="Senegal"<% if (mPais.equals("Senegal")) {%> selected <% } %>>Senegal</option>
<option value="Sierra Leona"<% if (mPais.equals("Sierra Leona")) {%> selected <% } %>>Sierra Leona</option>
<option value="Siria"<% if (mPais.equals("Siria")) {%> selected <% } %>>Siria</option>
<option value="Somalia"<% if (mPais.equals("Somalia")) {%> selected <% } %>>Somalia</option>
<option value="Sri Lanka"<% if (mPais.equals("Sri Lanka")) {%> selected <% } %>>Sri Lanka</option>
<option value="Sudáfrica"<% if (mPais.equals("Sudáfrica")) {%> selected <% } %>>Sudáfrica</option>
<option value="Sudán"<% if (mPais.equals("Sudán")) {%> selected <% } %>>Sudán</option>
<option value="Suecia"<% if (mPais.equals("Suecia")) {%> selected <% } %>>Suecia</option>
<option value="Suiza"<% if (mPais.equals("Suiza")) {%> selected <% } %>>Suiza</option>
<option value="Surinam"<% if (mPais.equals("Surinam")) {%> selected <% } %>>Surinam</option>
<option value="Tailandia"<% if (mPais.equals("Tailandia")) {%> selected <% } %>>Tailandia</option>
<option value="Taiwán"<% if (mPais.equals("Taiwán")) {%> selected <% } %>>Taiwán</option>
<option value="Tanzania"<% if (mPais.equals("Tanzania")) {%> selected <% } %>>Tanzania</option>
<option value="Togo"<% if (mPais.equals("Togo")) {%> selected <% } %>>Togo</option>
<option value="Trinidad y Tobago"<% if (mPais.equals("Trinidad y Tobago")) {%> selected <% } %>>Trinidad y Tobago</option>
<option value="Túnez"<% if (mPais.equals("Túnez")) {%> selected <% } %>>Túnez</option>
<option value="Turquía"<% if (mPais.equals("Turquía")) {%> selected <% } %>>Turquía</option>
<option value="Ucrania"<% if (mPais.equals("Ucrania")) {%> selected <% } %>>Ucrania</option>
<option value="Uganda"<% if (mPais.equals("Uganda")) {%> selected <% } %>>Uganda</option>
<option value="Uruguay"<% if (mPais.equals("Uruguay")) {%> selected <% } %>>Uruguay</option>
<option value="Venezuela"<% if (mPais.equals("Venezuela")) {%> selected <% } %>>Venezuela</option>
<option value="Vietnam"<% if (mPais.equals("Vietnam")) {%> selected <% } %>>Vietnam</option>
<option value="Yemen"<% if (mPais.equals("Yemen")) {%> selected <% } %>>Yemen</option>
<option value="Yugoslavia"<% if (mPais.equals("Yugoslavia")) {%> selected <% } %>>Yugoslavia</option>
<option value="Zaire"<% if (mPais.equals("Zaire")) {%> selected <% } %>>Zaire</option>
<option value="Zambia"<% if (mPais.equals("Zambia")) {%> selected <% } %>>Zambia</option>
<option value="Zimbabwe"<% if (mPais.equals("Zimbabwe")) {%> selected <% } %>>Zimbabwe</option>